# Generated by Django 5.0.6 on 2024-05-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.coursesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('parents_phone', models.IntegerField()),
                ('telegram_link', models.TextField()),
                ('address', models.TextField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.coursesmodel')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.teachersmodel')),
            ],
        ),
    ]
